FROM quay.io/actcat/buildpack_base:latest

MAINTAINER Vexus2 <hikaru.tooyama@gmail.com>

# Install node.js and npm
RUN curl -sL https://deb.nodesource.com/setup | sudo bash -
RUN apt-get update -y && apt-get install -y nodejs
